### ISSUE TITLE
Support Solr 6.0

### ISSUE THREAD

**Issue by adoerler** [TYPO3-Solr/solr-typo3-plugin#2]
Hello Ingo,

is it possible to provide a JAR file for Solr 6.0.0?

Typo3-Solr seems to run fine with Solr 6.0.0 until the queryParser plugin "org.typo3.solr.search.AccessFilterQParserPlugin" gets enabled.

I've tried to use the 1.5.0. release on Solr 6.0.0 but the following error appears while registering the core:

```
org.apache.solr.common.SolrException: Error CREATEing SolrCore 'example': Unable to create core [example] Caused by: org.apache.solr.core.SolrInfoMBean
...
Caused by: org.apache.solr.common.SolrException: Unable to create core [example]
...
Caused by: org.apache.solr.common.SolrException: org/apache/solr/core/SolrInfoMBean
...
Caused by: java.lang.NoClassDefFoundError: org/apache/solr/core/SolrInfoMBean
...
Caused by: java.lang.ClassNotFoundException: org.apache.solr.core.SolrInfoMBean
```

I'm aware that SOLR 6.0.0 is not an official release for now, but I would be very happy if it would work out with solr-typo3-plugin.

Kind regards from Austria
Andreas

**Comment by irnnr** [comment]
If somone provides a patch to make it work, we'll gladly support 6.0. For now we don't support it. The current plugin does not even work with 5.3 due to some changes we still have to adjust to. We will support 6.0 once the extension needs it.

**Comment by adoerler** [comment]
Hi Ingo,

thank you for your fast response.

I've just tried to build 5.3 and 6.0. You are absolutly right, two tests will fail even on 5.3.
With 6.0.0 on the other hand, the system didn't find solr-test-framework:jar:6.0.0 and solr-core:jar:6.0.0 which is no wonder as it is no official release.

As I do not really have a clue where to start (just copied the compile steps from Travis :-), I'll have to stick with SOLR 5.1.0 oder 5.2.0 for now (if a Typo3 project depends on access restrictions).

Kind regards
Andreas

**Comment by timoschmidt** [comment]
@adoerler 
@irnnr 

I've ported the plugin for Apache Solr 6.0.1 all tests are green. Can you maybe check if anything is working for you and we can merge this pr?

**Comment by timohund** [comment]
We've published version 1.6.1 (For Apache Solr 6.1.0) 

https://github.com/TYPO3-Solr/solr-typo3-plugin/releases/tag/release-1_6_1

**Comment by irnnr** [comment]
@timohund did you test this with 6.2 as well?
